# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/protobuf/struct_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("identity/admin/admin.proto", :syntax => :proto3) do
    add_message "depot.devtools.auth.v0.identity.admin.CreateIdentityRequest" do
      optional :data, :message, 1, "google.protobuf.Struct"
      optional :connection_id, :string, 2
      optional :schema_id, :string, 3
    end
    add_message "depot.devtools.auth.v0.identity.admin.CreateIdentityResponse" do
      optional :identity_id, :string, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdentitiesRequest" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdentitiesResponse" do
      repeated :identities, :message, 1, "depot.devtools.auth.v0.identity.admin.GetIdentitiesResponse.Identity"
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdentitiesResponse.Identity" do
      optional :identity_id, :string, 1
      optional :created_at, :message, 2, "google.protobuf.Timestamp"
      optional :updated_at, :message, 3, "google.protobuf.Timestamp"
      optional :main_identifier, :string, 4
      optional :schema_id, :string, 5
      optional :lock, :enum, 6, "depot.devtools.auth.v0.identity.admin.GetIdentitiesResponse.Lock"
    end
    add_enum "depot.devtools.auth.v0.identity.admin.GetIdentitiesResponse.Lock" do
      value :UNLOCKED, 0
      value :ADMIN_LOCKED, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdentityRequest" do
      optional :identity_id, :string, 2
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdentityResponse" do
      optional :identity_id, :string, 1
      optional :created_at, :message, 2, "google.protobuf.Timestamp"
      optional :updated_at, :message, 3, "google.protobuf.Timestamp"
      optional :main_identifier, :string, 4
      optional :traits_id, :string, 5
      repeated :addresses_ids, :string, 6
      map :credentials_ids, :string, :string, 7
      optional :schema_id, :string, 8
      optional :lock, :enum, 9, "depot.devtools.auth.v0.identity.admin.GetIdentityResponse.Lock"
    end
    add_enum "depot.devtools.auth.v0.identity.admin.GetIdentityResponse.Lock" do
      value :UNLOCKED, 0
      value :ADMIN_LOCKED, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeRequest" do
      optional :attribute, :string, 1
      optional :value, :string, 2
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse" do
      repeated :identities, :message, 1, "depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse.Identity"
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse.Identity" do
      optional :identity_id, :string, 1
      optional :created_at, :message, 2, "google.protobuf.Timestamp"
      optional :updated_at, :message, 3, "google.protobuf.Timestamp"
      optional :main_identifier, :string, 4
      optional :traits_id, :string, 5
      repeated :addresses_ids, :string, 6
      map :credentials_ids, :string, :string, 7
      optional :schema_id, :string, 8
      optional :lock, :enum, 9, "depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse.Identity.Lock"
    end
    add_enum "depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse.Identity.Lock" do
      value :UNLOCKED, 0
      value :ADMIN_LOCKED, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateIdentityRequest" do
      optional :identity_id, :string, 1
      optional :lock, :enum, 2, "depot.devtools.auth.v0.identity.admin.UpdateIdentityRequest.Lock"
    end
    add_enum "depot.devtools.auth.v0.identity.admin.UpdateIdentityRequest.Lock" do
      value :UNLOCKED, 0
      value :ADMIN_LOCKED, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateIdentityResponse" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.DeleteIdentityRequest" do
      optional :identity_id, :string, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.DeleteIdentityResponse" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetCredentialsRequest" do
      optional :identity_id, :string, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetCredentialsResponse" do
      map :credentials, :string, :message, 1, "depot.devtools.auth.v0.identity.admin.GetCredentialsResponse.Credential"
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetCredentialsResponse.Credential" do
      optional :credential_id, :string, 1
      optional :created_at, :message, 2, "google.protobuf.Timestamp"
      optional :updated_at, :message, 3, "google.protobuf.Timestamp"
      optional :identity_id, :string, 4
      optional :type, :int32, 5
      optional :name, :string, 6
      optional :configured, :bool, 7
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateCredentialRequest" do
      optional :data, :message, 1, "google.protobuf.Struct"
      optional :connection_id, :string, 2
      optional :identity_id, :string, 3
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateCredentialResponse" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.CreateConnectionRequest" do
      optional :name, :string, 1
      optional :client_id, :string, 2
      optional :client_secret, :string, 3
      optional :button_image_url, :string, 4
      optional :provider, :enum, 6, "depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers"
      optional :oidc_discovery_url, :string, 7
      repeated :mfa, :string, 8
      optional :type, :enum, 9, "depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Types"
      optional :scopes, :string, 10
    end
    add_enum "depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers" do
      value :NONE, 0
      value :OPENID, 1
      value :AMAZON, 2
      value :BITBUCKET, 3
      value :BOX, 4
      value :DAILYMOTION, 5
      value :DEEZER, 6
      value :DIGITALOCEAN, 7
      value :DISCORD, 8
      value :DROPBOX, 9
      value :EVEONLINE, 10
      value :FACEBOOK, 11
      value :FITBIT, 12
      value :GITEA, 13
      value :GITHUB, 14
      value :GITLAB, 15
      value :GOOGLE, 16
      value :SHOPIFY, 18
      value :SOUNDCLOUD, 19
      value :SPOTIFY, 20
      value :STEAM, 21
      value :STRIPE, 22
      value :TWITCH, 23
      value :UBER, 24
      value :WEPAY, 25
      value :YAHOO, 26
      value :YAMMER, 27
      value :HEROKU, 28
      value :INSTAGRAM, 29
      value :INTERCOM, 30
      value :KAKAO, 31
      value :LASTFM, 32
      value :LINKEDIN, 33
      value :LINE, 34
      value :ONEDRIVE, 35
      value :AZUREAD, 36
      value :MICROSOFTONLINE, 37
      value :BATTLENET, 38
      value :PAYPAL, 39
      value :TWITTER, 40
      value :SALESFORCE, 41
      value :TYPETALK, 42
      value :SLACK, 43
      value :MEETUP, 44
      value :XERO, 46
      value :VK, 47
      value :NAVER, 48
      value :YANDEX, 49
      value :NEXTCLOUD, 50
      value :APPLE, 52
      value :STRAVA, 53
    end
    add_enum "depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Types" do
      value :UNSET, 0
      value :PASSWORD, 1
      value :OTP, 2
      value :TOTP, 3
      value :OIDC, 4
    end
    add_message "depot.devtools.auth.v0.identity.admin.CreateConnectionResponse" do
      optional :name, :string, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetConnectionsRequest" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetConnectionsResponse" do
      repeated :connections, :message, 1, "depot.devtools.auth.v0.identity.admin.GetConnectionsResponse.Connection"
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetConnectionsResponse.Connection" do
      optional :name, :string, 1
      optional :client_id, :string, 2
      optional :client_secret, :string, 3
      optional :button_image_url, :string, 4
      optional :provider, :enum, 6, "depot.devtools.auth.v0.identity.admin.GetConnectionsResponse.Providers"
      optional :oidc_discovery_url, :string, 7
      repeated :mfa, :string, 8
      optional :type, :enum, 9, "depot.devtools.auth.v0.identity.admin.GetConnectionsResponse.Types"
      optional :id, :string, 10
      optional :scopes, :string, 11
      optional :purpose, :enum, 12, "depot.devtools.auth.v0.identity.admin.GetConnectionsResponse.Purposes"
    end
    add_enum "depot.devtools.auth.v0.identity.admin.GetConnectionsResponse.Providers" do
      value :NONE, 0
      value :OPENID, 1
      value :AMAZON, 2
      value :BITBUCKET, 3
      value :BOX, 4
      value :DAILYMOTION, 5
      value :DEEZER, 6
      value :DIGITALOCEAN, 7
      value :DISCORD, 8
      value :DROPBOX, 9
      value :EVEONLINE, 10
      value :FACEBOOK, 11
      value :FITBIT, 12
      value :GITEA, 13
      value :GITHUB, 14
      value :GITLAB, 15
      value :GOOGLE, 16
      value :SHOPIFY, 18
      value :SOUNDCLOUD, 19
      value :SPOTIFY, 20
      value :STEAM, 21
      value :STRIPE, 22
      value :TWITCH, 23
      value :UBER, 24
      value :WEPAY, 25
      value :YAHOO, 26
      value :YAMMER, 27
      value :HEROKU, 28
      value :INSTAGRAM, 29
      value :INTERCOM, 30
      value :KAKAO, 31
      value :LASTFM, 32
      value :LINKEDIN, 33
      value :LINE, 34
      value :ONEDRIVE, 35
      value :AZUREAD, 36
      value :MICROSOFTONLINE, 37
      value :BATTLENET, 38
      value :PAYPAL, 39
      value :TWITTER, 40
      value :SALESFORCE, 41
      value :TYPETALK, 42
      value :SLACK, 43
      value :MEETUP, 44
      value :XERO, 46
      value :VK, 47
      value :NAVER, 48
      value :YANDEX, 49
      value :NEXTCLOUD, 50
      value :APPLE, 52
      value :STRAVA, 53
    end
    add_enum "depot.devtools.auth.v0.identity.admin.GetConnectionsResponse.Types" do
      value :UNSET, 0
      value :PASSWORD, 1
      value :OTP, 2
      value :TOTP, 3
      value :OIDC, 4
    end
    add_enum "depot.devtools.auth.v0.identity.admin.GetConnectionsResponse.Purposes" do
      value :PURPOSE_UNKNOWN, 0
      value :PURPOSE_MAIN_FACTOR, 1
      value :PURPOSE_SECOND_FACTOR, 2
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateConnectionRequest" do
      optional :name, :string, 1
      optional :client_id, :string, 2
      optional :client_secret, :string, 3
      optional :button_image_url, :string, 4
      optional :provider, :enum, 6, "depot.devtools.auth.v0.identity.admin.UpdateConnectionRequest.Providers"
      optional :oidc_discovery_url, :string, 7
      repeated :mfa, :string, 8
      optional :type, :enum, 9, "depot.devtools.auth.v0.identity.admin.UpdateConnectionRequest.Types"
      optional :id, :string, 10
      optional :scopes, :string, 11
    end
    add_enum "depot.devtools.auth.v0.identity.admin.UpdateConnectionRequest.Providers" do
      value :NONE, 0
      value :OPENID, 1
      value :AMAZON, 2
      value :BITBUCKET, 3
      value :BOX, 4
      value :DAILYMOTION, 5
      value :DEEZER, 6
      value :DIGITALOCEAN, 7
      value :DISCORD, 8
      value :DROPBOX, 9
      value :EVEONLINE, 10
      value :FACEBOOK, 11
      value :FITBIT, 12
      value :GITEA, 13
      value :GITHUB, 14
      value :GITLAB, 15
      value :GOOGLE, 16
      value :SHOPIFY, 18
      value :SOUNDCLOUD, 19
      value :SPOTIFY, 20
      value :STEAM, 21
      value :STRIPE, 22
      value :TWITCH, 23
      value :UBER, 24
      value :WEPAY, 25
      value :YAHOO, 26
      value :YAMMER, 27
      value :HEROKU, 28
      value :INSTAGRAM, 29
      value :INTERCOM, 30
      value :KAKAO, 31
      value :LASTFM, 32
      value :LINKEDIN, 33
      value :LINE, 34
      value :ONEDRIVE, 35
      value :AZUREAD, 36
      value :MICROSOFTONLINE, 37
      value :BATTLENET, 38
      value :PAYPAL, 39
      value :TWITTER, 40
      value :SALESFORCE, 41
      value :TYPETALK, 42
      value :SLACK, 43
      value :MEETUP, 44
      value :XERO, 46
      value :VK, 47
      value :NAVER, 48
      value :YANDEX, 49
      value :NEXTCLOUD, 50
      value :APPLE, 52
      value :STRAVA, 53
    end
    add_enum "depot.devtools.auth.v0.identity.admin.UpdateConnectionRequest.Types" do
      value :UNSET, 0
      value :PASSWORD, 1
      value :OTP, 2
      value :TOTP, 3
      value :OIDC, 4
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateConnectionResponse" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.DeleteConnectionRequest" do
      optional :id, :string, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.DeleteConnectionResponse" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetOAuth2ClientsRequest" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetOAuth2ClientsResponse" do
      repeated :clients, :message, 1, "depot.devtools.auth.v0.identity.admin.GetOAuth2ClientsResponse.Client"
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetOAuth2ClientsResponse.Client" do
      repeated :allowed_cors_origins, :string, 1
      repeated :audience, :string, 2
      optional :backchannel_logout_session_required, :bool, 3
      optional :backchannel_logout_uri, :string, 4
      optional :client_id, :string, 5
      optional :client_name, :string, 6
      optional :client_secret_expires_at, :int64, 7
      optional :client_uri, :string, 8
      repeated :contacts, :string, 9
      optional :created_at, :message, 10, "google.protobuf.Timestamp"
      optional :frontchannel_logout_session_required, :bool, 11
      optional :frontchannel_logout_uri, :string, 12
      repeated :grant_types, :enum, 13, "depot.devtools.auth.v0.identity.admin.GrantType"
      optional :jwks, :message, 14, "google.protobuf.Struct"
      optional :jwks_uri, :string, 15
      optional :logo_uri, :string, 16
      optional :metadata, :message, 17, "google.protobuf.Struct"
      optional :owner, :string, 18
      optional :policy_uri, :string, 19
      repeated :post_logout_redirect_uris, :string, 20
      repeated :redirect_uris, :string, 21
      optional :request_object_signing_alg, :enum, 22, "depot.devtools.auth.v0.identity.admin.RequestObjectSigningAlg"
      repeated :request_uris, :string, 23
      repeated :response_types, :enum, 24, "depot.devtools.auth.v0.identity.admin.ResponseType"
      optional :scope, :string, 25
      optional :sector_identifier_uri, :string, 26
      optional :subject_type, :enum, 27, "depot.devtools.auth.v0.identity.admin.SubjectType"
      optional :token_endpoint_auth_method, :enum, 28, "depot.devtools.auth.v0.identity.admin.TokenEndpointAuthMethod"
      optional :token_endpoint_auth_signing_alg, :enum, 29, "depot.devtools.auth.v0.identity.admin.TokenEndpointAuthSigningAlg"
      optional :tos_uri, :string, 30
      optional :updated_at, :message, 31, "google.protobuf.Timestamp"
      optional :userinfo_signed_response_alg, :enum, 32, "depot.devtools.auth.v0.identity.admin.UserinfoSignedResponseAlg"
      optional :client_type, :enum, 33, "depot.devtools.auth.v0.identity.admin.ClientType"
    end
    add_message "depot.devtools.auth.v0.identity.admin.CreateOAuth2ClientRequest" do
      repeated :allowed_cors_origins, :string, 1
      repeated :audience, :string, 2
      optional :backchannel_logout_session_required, :bool, 3
      optional :backchannel_logout_uri, :string, 4
      optional :client_name, :string, 6
      optional :client_uri, :string, 8
      repeated :contacts, :string, 9
      optional :frontchannel_logout_session_required, :bool, 11
      optional :frontchannel_logout_uri, :string, 12
      repeated :grant_types, :enum, 13, "depot.devtools.auth.v0.identity.admin.GrantType"
      optional :jwks, :message, 14, "google.protobuf.Struct"
      optional :jwks_uri, :string, 15
      optional :logo_uri, :string, 16
      optional :metadata, :message, 17, "google.protobuf.Struct"
      optional :owner, :string, 18
      optional :policy_uri, :string, 19
      repeated :post_logout_redirect_uris, :string, 20
      repeated :redirect_uris, :string, 21
      optional :request_object_signing_alg, :enum, 22, "depot.devtools.auth.v0.identity.admin.RequestObjectSigningAlg"
      repeated :request_uris, :string, 23
      repeated :response_types, :enum, 24, "depot.devtools.auth.v0.identity.admin.ResponseType"
      optional :scope, :string, 25
      optional :sector_identifier_uri, :string, 26
      optional :subject_type, :enum, 27, "depot.devtools.auth.v0.identity.admin.SubjectType"
      optional :token_endpoint_auth_method, :enum, 28, "depot.devtools.auth.v0.identity.admin.TokenEndpointAuthMethod"
      optional :token_endpoint_auth_signing_alg, :enum, 29, "depot.devtools.auth.v0.identity.admin.TokenEndpointAuthSigningAlg"
      optional :tos_uri, :string, 30
      optional :userinfo_signed_response_alg, :enum, 31, "depot.devtools.auth.v0.identity.admin.UserinfoSignedResponseAlg"
      optional :client_secret, :string, 32
      optional :client_type, :enum, 33, "depot.devtools.auth.v0.identity.admin.ClientType"
    end
    add_message "depot.devtools.auth.v0.identity.admin.CreateOAuth2ClientResponse" do
      optional :client_id, :string, 1
      optional :client_secret, :string, 2
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateOAuth2ClientRequest" do
      repeated :allowed_cors_origins, :string, 1
      repeated :audience, :string, 2
      optional :backchannel_logout_session_required, :bool, 3
      optional :backchannel_logout_uri, :string, 4
      optional :client_name, :string, 6
      optional :client_uri, :string, 8
      repeated :contacts, :string, 9
      optional :frontchannel_logout_session_required, :bool, 11
      optional :frontchannel_logout_uri, :string, 12
      repeated :grant_types, :enum, 13, "depot.devtools.auth.v0.identity.admin.GrantType"
      optional :jwks, :message, 14, "google.protobuf.Struct"
      optional :jwks_uri, :string, 15
      optional :logo_uri, :string, 16
      optional :metadata, :message, 17, "google.protobuf.Struct"
      optional :owner, :string, 18
      optional :policy_uri, :string, 19
      repeated :post_logout_redirect_uris, :string, 20
      repeated :redirect_uris, :string, 21
      optional :request_object_signing_alg, :enum, 22, "depot.devtools.auth.v0.identity.admin.RequestObjectSigningAlg"
      repeated :request_uris, :string, 23
      repeated :response_types, :enum, 24, "depot.devtools.auth.v0.identity.admin.ResponseType"
      optional :scope, :string, 25
      optional :sector_identifier_uri, :string, 26
      optional :subject_type, :enum, 27, "depot.devtools.auth.v0.identity.admin.SubjectType"
      optional :token_endpoint_auth_method, :enum, 28, "depot.devtools.auth.v0.identity.admin.TokenEndpointAuthMethod"
      optional :token_endpoint_auth_signing_alg, :enum, 29, "depot.devtools.auth.v0.identity.admin.TokenEndpointAuthSigningAlg"
      optional :tos_uri, :string, 30
      optional :userinfo_signed_response_alg, :enum, 31, "depot.devtools.auth.v0.identity.admin.UserinfoSignedResponseAlg"
      optional :client_secret, :string, 32
      optional :client_id, :string, 33
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateOAuth2ClientResponse" do
      optional :client_id, :string, 1
      optional :client_secret, :string, 2
    end
    add_message "depot.devtools.auth.v0.identity.admin.DeleteOAuth2ClientRequest" do
      optional :client_id, :string, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.DeleteOAuth2ClientResponse" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetAddressesRequest" do
      optional :identity_id, :string, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetAddressesResponse" do
      repeated :addresses, :message, 1, "depot.devtools.auth.v0.identity.admin.GetAddressesResponse.Address"
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetAddressesResponse.Address" do
      optional :id, :string, 1
      optional :identity_id, :string, 2
      optional :name, :string, 3
      optional :address, :string, 4
      optional :verified, :bool, 5
      optional :id_schema_key, :string, 6
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetAddressRequest" do
      oneof :match do
        optional :id, :string, 1
        optional :verification, :string, 2
      end
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetAddressResponse" do
      optional :id, :string, 1
      optional :identity_id, :string, 2
      optional :name, :string, 3
      optional :address, :string, 4
      optional :verified, :bool, 5
      optional :id_schema_key, :string, 6
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateAddressRequest" do
      optional :id, :string, 1
      oneof :attribute do
        optional :verified, :bool, 2
        optional :address, :string, 3
      end
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateAddressResponse" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetTraitsRequest" do
      optional :identity_id, :string, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetTraitsResponse" do
      optional :traits, :string, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateTraitsRequest" do
      optional :identity_id, :string, 1
      optional :traits, :string, 2
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateTraitsResponse" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdentityLoginAttemptsRequest" do
      optional :identity_id, :string, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdentityLoginAttemptsResponse" do
      repeated :attempts, :message, 1, "depot.devtools.auth.v0.identity.admin.GetIdentityLoginAttemptsResponse.Attempt"
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdentityLoginAttemptsResponse.Attempt" do
      optional :id, :string, 1
      optional :identity_id, :string, 2
      optional :status, :string, 3
      repeated :authentication_methods, :string, 4
      optional :created_at, :message, 5, "google.protobuf.Timestamp"
      optional :expires_at, :message, 6, "google.protobuf.Timestamp"
    end
    add_message "depot.devtools.auth.v0.identity.admin.CreateIdSchemaRequest" do
      optional :name, :string, 1
      optional :content, :message, 2, "google.protobuf.Struct"
    end
    add_message "depot.devtools.auth.v0.identity.admin.CreateIdSchemaResponse" do
      optional :id, :string, 2
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdSchemasRequest" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdSchemasResponse" do
      repeated :jsonschemas, :message, 1, "depot.devtools.auth.v0.identity.admin.GetIdSchemasResponse.JsonSchema"
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdSchemasResponse.JsonSchema" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :content, :message, 3, "google.protobuf.Struct"
      optional :created_at, :message, 4, "google.protobuf.Timestamp"
      optional :updated_at, :message, 5, "google.protobuf.Timestamp"
      optional :is_default, :bool, 6
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdSchemaRequest" do
      optional :id, :string, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetIdSchemaResponse" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :content, :message, 3, "google.protobuf.Struct"
      optional :created_at, :message, 4, "google.protobuf.Timestamp"
      optional :updated_at, :message, 5, "google.protobuf.Timestamp"
      optional :is_default, :bool, 6
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetDefaultIdSchemaRequest" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetDefaultIdSchemaResponse" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :content, :message, 3, "google.protobuf.Struct"
      optional :created_at, :message, 4, "google.protobuf.Timestamp"
      optional :updated_at, :message, 5, "google.protobuf.Timestamp"
      optional :is_default, :bool, 6
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateIdSchemaRequest" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :content, :message, 3, "google.protobuf.Struct"
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateIdSchemaResponse" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.MarkDefaultIdSchemaRequest" do
      optional :id, :string, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.MarkDefaultIdSchemaResponse" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.DeleteIdSchemaRequest" do
      optional :id, :string, 1
    end
    add_message "depot.devtools.auth.v0.identity.admin.DeleteIdSchemaResponse" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetEmailsSetupRequest" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetEmailsSetupResponse" do
      optional :welcome, :message, 1, "depot.devtools.auth.v0.identity.admin.GetEmailsSetupResponse.EmailTemplate"
      optional :account_verification, :message, 2, "depot.devtools.auth.v0.identity.admin.GetEmailsSetupResponse.EmailTemplate"
      optional :account_recovery, :message, 3, "depot.devtools.auth.v0.identity.admin.GetEmailsSetupResponse.EmailTemplate"
      optional :account_recovered, :message, 4, "depot.devtools.auth.v0.identity.admin.GetEmailsSetupResponse.EmailTemplate"
      optional :otp, :message, 5, "depot.devtools.auth.v0.identity.admin.GetEmailsSetupResponse.EmailTemplate"
      optional :smtp, :message, 6, "depot.devtools.auth.v0.identity.admin.GetEmailsSetupResponse.EmailSender"
      optional :project_id, :string, 7
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetEmailsSetupResponse.EmailTemplate" do
      optional :content, :string, 3
      optional :subject, :string, 4
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetEmailsSetupResponse.EmailSender" do
      optional :email_address, :string, 1
      optional :smtp_host, :string, 2
      optional :smtp_port, :uint32, 3
      optional :smtp_username, :string, 4
      optional :smtp_password, :string, 5
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest" do
      optional :welcome, :message, 1, "depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate"
      optional :account_verification, :message, 2, "depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate"
      optional :account_recovery, :message, 3, "depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate"
      optional :account_recovered, :message, 4, "depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate"
      optional :otp, :message, 5, "depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate"
      optional :smtp, :message, 6, "depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailSender"
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate" do
      optional :content, :string, 1
      optional :subject, :string, 2
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailSender" do
      optional :email_address, :string, 1
      optional :smtp_host, :string, 2
      optional :smtp_port, :uint32, 3
      optional :smtp_username, :string, 4
      optional :smtp_password, :string, 5
    end
    add_message "depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupResponse" do
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetUserBaseStatisticsRequest" do
      optional :days_before, :uint32, 1
      optional :lifetime_start_at, :message, 2, "google.protobuf.Timestamp"
      optional :lifetime_end_at, :message, 3, "google.protobuf.Timestamp"
    end
    add_message "depot.devtools.auth.v0.identity.admin.GetUserBaseStatisticsResponse" do
      optional :total_users, :int32, 1
      map :users_per_day, :string, :int32, 2
      map :sessions_per_day, :string, :int32, 3
      optional :total_active_users, :int32, 4
      optional :total_lifetime_used, :double, 5
    end
    add_enum "depot.devtools.auth.v0.identity.admin.ClientType" do
      value :CLIENT_TYPE_UNSET, 0
      value :CLIENT_FIRST_PARTY, 1
      value :CLIENT_THIRD_PARTY, 2
      value :CLIENT_SYSTEM_PARTY, 3
    end
    add_enum "depot.devtools.auth.v0.identity.admin.SubjectType" do
      value :SUBJECT_TYPE_PUBLIC, 0
      value :SUBJECT_TYPE_PAIRWISE, 1
    end
    add_enum "depot.devtools.auth.v0.identity.admin.TokenEndpointAuthMethod" do
      value :TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_BASIC, 0
      value :TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_POST, 1
      value :TOKEN_ENDPOINT_AUTH_METHOD_PRIVATE_KEY_JWT, 2
      value :TOKEN_ENDPOINT_AUTH_METHOD_NONE, 3
    end
    add_enum "depot.devtools.auth.v0.identity.admin.TokenEndpointAuthSigningAlg" do
      value :TOKEN_ENDPOINT_AUTH_SIGNING_ALG_UNSET, 0
      value :TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS256, 1
      value :TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS384, 2
      value :TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS512, 3
      value :TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS256, 4
      value :TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS384, 5
      value :TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS512, 6
      value :TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES256, 7
      value :TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES384, 8
      value :TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES512, 9
    end
    add_enum "depot.devtools.auth.v0.identity.admin.GrantType" do
      value :GRANT_TYPE_UNSET, 0
      value :GRANT_TYPE_CLIENT_CREDENTIALS, 1
      value :GRANT_TYPE_AUTHORIZATION_CODE, 2
      value :GRANT_TYPE_IMPLICIT, 3
      value :GRANT_TYPE_REFRESH_TOKEN, 4
      value :GRANT_TYPE_DEVICE_CODE, 5
    end
    add_enum "depot.devtools.auth.v0.identity.admin.ResponseType" do
      value :RESPONSE_TYPE_UNSET, 0
      value :RESPONSE_TYPE_NONE, 1
      value :RESPONSE_TYPE_ID_TOKEN, 2
      value :RESPONSE_TYPE_TOKEN, 3
      value :RESPONSE_TYPE_CODE, 4
      value :RESPONSE_TYPE_ID_TOKEN_TOKEN, 5
      value :RESPONSE_TYPE_CODE_ID_TOKEN, 6
      value :RESPONSE_TYPE_CODE_TOKEN, 7
      value :RESPONSE_TYPE_CODE_ID_TOKEN_TOKEN, 8
    end
    add_enum "depot.devtools.auth.v0.identity.admin.RequestObjectSigningAlg" do
      value :REQUEST_OBJECT_SIGNING_ALG_UNSET, 0
      value :REQUEST_OBJECT_SIGNING_ALG_NONE, 1
      value :REQUEST_OBJECT_SIGNING_ALG_RS256, 2
    end
    add_enum "depot.devtools.auth.v0.identity.admin.UserinfoSignedResponseAlg" do
      value :USERINFO_SIGNED_RESPONSE_ALG_UNSET, 0
      value :USERINFO_SIGNED_RESPONSE_ALG_NONE, 1
      value :USERINFO_SIGNED_RESPONSE_ALG_RS256, 2
    end
  end
end

module Auth3
  module Identity
    module Admin
      CreateIdentityRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.CreateIdentityRequest").msgclass
      CreateIdentityResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.CreateIdentityResponse").msgclass
      GetIdentitiesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdentitiesRequest").msgclass
      GetIdentitiesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdentitiesResponse").msgclass
      GetIdentitiesResponse::Identity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdentitiesResponse.Identity").msgclass
      GetIdentitiesResponse::Lock = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdentitiesResponse.Lock").enummodule
      GetIdentityRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdentityRequest").msgclass
      GetIdentityResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdentityResponse").msgclass
      GetIdentityResponse::Lock = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdentityResponse.Lock").enummodule
      GetIdentitiesByAttributeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeRequest").msgclass
      GetIdentitiesByAttributeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse").msgclass
      GetIdentitiesByAttributeResponse::Identity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse.Identity").msgclass
      GetIdentitiesByAttributeResponse::Identity::Lock = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse.Identity.Lock").enummodule
      UpdateIdentityRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateIdentityRequest").msgclass
      UpdateIdentityRequest::Lock = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateIdentityRequest.Lock").enummodule
      UpdateIdentityResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateIdentityResponse").msgclass
      DeleteIdentityRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.DeleteIdentityRequest").msgclass
      DeleteIdentityResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.DeleteIdentityResponse").msgclass
      GetCredentialsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetCredentialsRequest").msgclass
      GetCredentialsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetCredentialsResponse").msgclass
      GetCredentialsResponse::Credential = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetCredentialsResponse.Credential").msgclass
      UpdateCredentialRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateCredentialRequest").msgclass
      UpdateCredentialResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateCredentialResponse").msgclass
      CreateConnectionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.CreateConnectionRequest").msgclass
      CreateConnectionRequest::Providers = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers").enummodule
      CreateConnectionRequest::Types = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Types").enummodule
      CreateConnectionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.CreateConnectionResponse").msgclass
      GetConnectionsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetConnectionsRequest").msgclass
      GetConnectionsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetConnectionsResponse").msgclass
      GetConnectionsResponse::Connection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetConnectionsResponse.Connection").msgclass
      GetConnectionsResponse::Providers = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetConnectionsResponse.Providers").enummodule
      GetConnectionsResponse::Types = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetConnectionsResponse.Types").enummodule
      GetConnectionsResponse::Purposes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetConnectionsResponse.Purposes").enummodule
      UpdateConnectionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateConnectionRequest").msgclass
      UpdateConnectionRequest::Providers = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateConnectionRequest.Providers").enummodule
      UpdateConnectionRequest::Types = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateConnectionRequest.Types").enummodule
      UpdateConnectionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateConnectionResponse").msgclass
      DeleteConnectionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.DeleteConnectionRequest").msgclass
      DeleteConnectionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.DeleteConnectionResponse").msgclass
      GetOAuth2ClientsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetOAuth2ClientsRequest").msgclass
      GetOAuth2ClientsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetOAuth2ClientsResponse").msgclass
      GetOAuth2ClientsResponse::Client = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetOAuth2ClientsResponse.Client").msgclass
      CreateOAuth2ClientRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.CreateOAuth2ClientRequest").msgclass
      CreateOAuth2ClientResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.CreateOAuth2ClientResponse").msgclass
      UpdateOAuth2ClientRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateOAuth2ClientRequest").msgclass
      UpdateOAuth2ClientResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateOAuth2ClientResponse").msgclass
      DeleteOAuth2ClientRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.DeleteOAuth2ClientRequest").msgclass
      DeleteOAuth2ClientResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.DeleteOAuth2ClientResponse").msgclass
      GetAddressesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetAddressesRequest").msgclass
      GetAddressesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetAddressesResponse").msgclass
      GetAddressesResponse::Address = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetAddressesResponse.Address").msgclass
      GetAddressRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetAddressRequest").msgclass
      GetAddressResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetAddressResponse").msgclass
      UpdateAddressRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateAddressRequest").msgclass
      UpdateAddressResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateAddressResponse").msgclass
      GetTraitsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetTraitsRequest").msgclass
      GetTraitsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetTraitsResponse").msgclass
      UpdateTraitsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateTraitsRequest").msgclass
      UpdateTraitsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateTraitsResponse").msgclass
      GetIdentityLoginAttemptsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdentityLoginAttemptsRequest").msgclass
      GetIdentityLoginAttemptsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdentityLoginAttemptsResponse").msgclass
      GetIdentityLoginAttemptsResponse::Attempt = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdentityLoginAttemptsResponse.Attempt").msgclass
      CreateIdSchemaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.CreateIdSchemaRequest").msgclass
      CreateIdSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.CreateIdSchemaResponse").msgclass
      GetIdSchemasRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdSchemasRequest").msgclass
      GetIdSchemasResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdSchemasResponse").msgclass
      GetIdSchemasResponse::JsonSchema = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdSchemasResponse.JsonSchema").msgclass
      GetIdSchemaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdSchemaRequest").msgclass
      GetIdSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetIdSchemaResponse").msgclass
      GetDefaultIdSchemaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetDefaultIdSchemaRequest").msgclass
      GetDefaultIdSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetDefaultIdSchemaResponse").msgclass
      UpdateIdSchemaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateIdSchemaRequest").msgclass
      UpdateIdSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateIdSchemaResponse").msgclass
      MarkDefaultIdSchemaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.MarkDefaultIdSchemaRequest").msgclass
      MarkDefaultIdSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.MarkDefaultIdSchemaResponse").msgclass
      DeleteIdSchemaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.DeleteIdSchemaRequest").msgclass
      DeleteIdSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.DeleteIdSchemaResponse").msgclass
      GetEmailsSetupRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetEmailsSetupRequest").msgclass
      GetEmailsSetupResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetEmailsSetupResponse").msgclass
      GetEmailsSetupResponse::EmailTemplate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetEmailsSetupResponse.EmailTemplate").msgclass
      GetEmailsSetupResponse::EmailSender = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetEmailsSetupResponse.EmailSender").msgclass
      UpdateEmailsSetupRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest").msgclass
      UpdateEmailsSetupRequest::EmailTemplate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate").msgclass
      UpdateEmailsSetupRequest::EmailSender = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailSender").msgclass
      UpdateEmailsSetupResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupResponse").msgclass
      GetUserBaseStatisticsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetUserBaseStatisticsRequest").msgclass
      GetUserBaseStatisticsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GetUserBaseStatisticsResponse").msgclass
      ClientType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.ClientType").enummodule
      SubjectType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.SubjectType").enummodule
      TokenEndpointAuthMethod = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.TokenEndpointAuthMethod").enummodule
      TokenEndpointAuthSigningAlg = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.TokenEndpointAuthSigningAlg").enummodule
      GrantType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.GrantType").enummodule
      ResponseType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.ResponseType").enummodule
      RequestObjectSigningAlg = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.RequestObjectSigningAlg").enummodule
      UserinfoSignedResponseAlg = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("depot.devtools.auth.v0.identity.admin.UserinfoSignedResponseAlg").enummodule
    end
  end
end
