# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: identity/admin/admin.proto for package 'Auth3.Identity.Admin'

require 'grpc'
require_relative 'admin_pb'

module Auth3
  module Identity
    module Admin
      module Admin
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'depot.devtools.auth.v0.identity.admin.Admin'

          rpc :CreateIdentity, ::Auth3::Identity::Admin::CreateIdentityRequest, ::Auth3::Identity::Admin::CreateIdentityResponse
          rpc :GetIdentity, ::Auth3::Identity::Admin::GetIdentityRequest, ::Auth3::Identity::Admin::GetIdentityResponse
          rpc :GetIdentityByIdentifier, ::Auth3::Identity::Admin::GetIdentityByIdentifierRequest, ::Auth3::Identity::Admin::GetIdentityByIdentifierResponse
          rpc :GetIdentitiesByAttribute, ::Auth3::Identity::Admin::GetIdentitiesByAttributeRequest, ::Auth3::Identity::Admin::GetIdentitiesByAttributeResponse
          rpc :GetIdentities, ::Auth3::Identity::Admin::GetIdentitiesRequest, ::Auth3::Identity::Admin::GetIdentitiesResponse
          rpc :UpdateIdentity, ::Auth3::Identity::Admin::UpdateIdentityRequest, ::Auth3::Identity::Admin::UpdateIdentityResponse
          rpc :DeleteIdentity, ::Auth3::Identity::Admin::DeleteIdentityRequest, ::Auth3::Identity::Admin::DeleteIdentityResponse
          rpc :GetAddresses, ::Auth3::Identity::Admin::GetAddressesRequest, ::Auth3::Identity::Admin::GetAddressesResponse
          rpc :GetAddress, ::Auth3::Identity::Admin::GetAddressRequest, ::Auth3::Identity::Admin::GetAddressResponse
          rpc :UpdateAddress, ::Auth3::Identity::Admin::UpdateAddressRequest, ::Auth3::Identity::Admin::UpdateAddressResponse
          rpc :GetTraits, ::Auth3::Identity::Admin::GetTraitsRequest, ::Auth3::Identity::Admin::GetTraitsResponse
          rpc :UpdateTraits, ::Auth3::Identity::Admin::UpdateTraitsRequest, ::Auth3::Identity::Admin::UpdateTraitsResponse
          rpc :GetCredentials, ::Auth3::Identity::Admin::GetCredentialsRequest, ::Auth3::Identity::Admin::GetCredentialsResponse
          rpc :UpdateCredential, ::Auth3::Identity::Admin::UpdateCredentialRequest, ::Auth3::Identity::Admin::UpdateCredentialResponse
          rpc :GetIdentityLoginAttempts, ::Auth3::Identity::Admin::GetIdentityLoginAttemptsRequest, ::Auth3::Identity::Admin::GetIdentityLoginAttemptsResponse
          rpc :CreateConnection, ::Auth3::Identity::Admin::CreateConnectionRequest, ::Auth3::Identity::Admin::CreateConnectionResponse
          rpc :GetConnections, ::Auth3::Identity::Admin::GetConnectionsRequest, ::Auth3::Identity::Admin::GetConnectionsResponse
          rpc :UpdateConnection, ::Auth3::Identity::Admin::UpdateConnectionRequest, ::Auth3::Identity::Admin::UpdateConnectionResponse
          rpc :DeleteConnection, ::Auth3::Identity::Admin::DeleteConnectionRequest, ::Auth3::Identity::Admin::DeleteConnectionResponse
          rpc :CreateIdSchema, ::Auth3::Identity::Admin::CreateIdSchemaRequest, ::Auth3::Identity::Admin::CreateIdSchemaResponse
          rpc :GetIdSchemas, ::Auth3::Identity::Admin::GetIdSchemasRequest, ::Auth3::Identity::Admin::GetIdSchemasResponse
          rpc :GetIdSchema, ::Auth3::Identity::Admin::GetIdSchemaRequest, ::Auth3::Identity::Admin::GetIdSchemaResponse
          rpc :GetDefaultIdSchema, ::Auth3::Identity::Admin::GetDefaultIdSchemaRequest, ::Auth3::Identity::Admin::GetDefaultIdSchemaResponse
          rpc :UpdateIdSchema, ::Auth3::Identity::Admin::UpdateIdSchemaRequest, ::Auth3::Identity::Admin::UpdateIdSchemaResponse
          rpc :MarkDefaultIdSchema, ::Auth3::Identity::Admin::MarkDefaultIdSchemaRequest, ::Auth3::Identity::Admin::MarkDefaultIdSchemaResponse
          rpc :DeleteIdSchema, ::Auth3::Identity::Admin::DeleteIdSchemaRequest, ::Auth3::Identity::Admin::DeleteIdSchemaResponse
          rpc :CreateOAuth2Client, ::Auth3::Identity::Admin::CreateOAuth2ClientRequest, ::Auth3::Identity::Admin::CreateOAuth2ClientResponse
          rpc :GetOAuth2Clients, ::Auth3::Identity::Admin::GetOAuth2ClientsRequest, ::Auth3::Identity::Admin::GetOAuth2ClientsResponse
          rpc :UpdateOAuth2Client, ::Auth3::Identity::Admin::UpdateOAuth2ClientRequest, ::Auth3::Identity::Admin::UpdateOAuth2ClientResponse
          rpc :DeleteOAuth2Client, ::Auth3::Identity::Admin::DeleteOAuth2ClientRequest, ::Auth3::Identity::Admin::DeleteOAuth2ClientResponse
          rpc :GetEmailsSetup, ::Auth3::Identity::Admin::GetEmailsSetupRequest, ::Auth3::Identity::Admin::GetEmailsSetupResponse
          rpc :UpdateEmailsSetup, ::Auth3::Identity::Admin::UpdateEmailsSetupRequest, ::Auth3::Identity::Admin::UpdateEmailsSetupResponse
          rpc :GetUserBaseStatistics, ::Auth3::Identity::Admin::GetUserBaseStatisticsRequest, ::Auth3::Identity::Admin::GetUserBaseStatisticsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
